{% set name = "hg-evolve" %}
{% set version = "9.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c7dec608ecca486363bd2e9343a8ae37ea6f3efed574afcfcb9c1fb7e26414cb

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python <3
  run:
    - python <3
    - mercurial

test:
  imports:
    - hgext3rd
    - hgext3rd.evolve
    - hgext3rd.evolve.thirdparty
    - hgext3rd.topic

about:
  home: https://www.mercurial-scm.org/doc/evolution/
  license: GPLv2+
  license_file: COPYING
  summary: Flexible evolution of Mercurial history.
  doc_url: https://www.mercurial-scm.org/doc/evolution/
  dev_url: https://www.mercurial-scm.org/repo/evolve/

extra:
  recipe-maintainers:
    - paugier
