{% set name = "hg-evolve" %}
{% set version = "10.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1fae41bc1eacc2d597ed18332fe2f938eef73db505860506cbe1bcc575a08be

build:
  noarch: python
  number: 0
  script: 'pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - mercurial

test:
  imports:
    - hgext3rd
    - hgext3rd.evolve
    - hgext3rd.evolve.thirdparty
    - hgext3rd.topic

about:
  home: https://www.mercurial-scm.org/doc/evolution/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Flexible evolution of Mercurial history.
  doc_url: https://www.mercurial-scm.org/doc/evolution/
  dev_url: https://www.mercurial-scm.org/repo/evolve/

extra:
  recipe-maintainers:
    - paugier
