travis:
  secure:
    BINSTAR_TOKEN: GMMSPhd3EQxSHKnrYU5/oudUgQW4d772NWL/qks9T7tF263v7CzpbleuvE2cVJ9fFwIUP0ueSnis9N8iDiaAFpyPvVeivKqcdD4XOeqIruXSar3jxuce88eC6GkoVt2sodqwNQv+WdkCP9ZXMLmIR1NQU9CuXUHLw7sc7XKmpBBiGV2VYxQbum93gPIhjqe58hXOQJeSvvXq2zkPTlz+Dpo4tjW3LAo3+4Z+mBqFMXWQ1tMhqB4wlP6Q0/tMJxIWhf8lfFtjrN97g54gdQJRAjr5A3Q0fB94K8TTSsvIRjtzZr5zPPRGK5BL842KK14xziD9HVTXvKZEXTeF96AZv6oU1QRSu67/38jCiO+38W7k3AiumsNkKF9+4GtRGNa9rUdTJFSCb4cElgImzlfGNEmYaDbfAX3s5NNVBSN25//L+jCB1eA8HA9JMVrz9u6fL8NOLSb1F2kk7+xliHHVIYhUYCbvZE6+rb1foDmcKdkUEJa0UBDgetmyyAo7geUDuA2KNJLEZXONGB3zd06gj6/cuuqPPlw6sss4BshdpcfEABzI99MD8HMpraHYgpcgxT93FkT86cHjUtIMQqp+zr8am+q7GhdgMdIPReGbeLrELnpgYJrrnzZw+A5eQXDzKFOGG6bBEwRSA0f13OsIgS0IDryeDnW4TwSTpl6QQrM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
